### ISSUE TITLE
Clarify release notes

### ISSUE THREAD

**Issue by drbenmorgan** [BxCppDev/Bayeux#10]
For SuperNEMO work when preparing new releases, it's helpful to have release notes with summary changes to streamline testing. Whilst there are notes, these don't outline major changes, making it necessary to go through the commit log.

For future releases, SuperNEMO would request that the notes be improved, at least to note which PRs have been merged in since the last release, and any breaking changes.

**Comment by fmauger** [comment]
ok, I'm working on it.
I will add an explicit current "release_notes.rst" file with an "archived_notes/" directory for history ith former "release_notes-ver.rst" files.	
I will try to follow the guidelines from this post: http://blog.davingranroth.com/2010/03/how-to-write-release-notes/ using the "One page of release notes per version" approach.

**Comment by fmauger** [comment]
The release notes will be filled manually, with only informations that can be considered as useful for users and for client packages.  So no "git log" output, but preferably some no-so-technical abstract.
