### ISSUE TITLE
definition of  Bayeux_INCLUDE_DIR for cmake 

### ISSUE THREAD

**Issue by emchauve** [BxCppDev/Bayeux#24]
https://github.com/BxCppDev/Bayeux/blob/83ac17ebd5831d89929146b7cbcd6aaeefac15a8/cmake/BayeuxConfig.cmake.in#L57-L58

Wondering why this two line were commented. I have to un-comment then in order to "cmake" any custom programs using Bayeux library. May be that was done on purpose and there is another way to manage dependency ?

**Comment by emchauve** [comment]
help!

**Comment by fmauger** [comment]
You should use:
```
project(test)
find_package(Bayeux REQUIRED)
add_executable(test test.cxx)
target_link_libraries(test Bayeux::Bayeux)
```
The linked target ``Bayeux::Bayeux`` automatically add the Bayeux include dir.
That's why the ``Bayeux_INCLUDE_DIRS`` CMake env is not needed anymore.

**Comment by emchauve** [comment]
thanks
