### ISSUE TITLE
Management of MC output file with empty events

### ISSUE THREAD

**Issue by fmauger** [BxCppDev/Bayeux#25]
Check what is the policy with MC events without any sensitive hits.
Do we store empty events or skip them?

**Comment by emchauve** [comment]
There will be "true information" to propagate, this could be a configurable option YES/NO on the processing to keep them or not ?

**Comment by fmauger** [comment]
The option already exists in the simulation manager.
It is a static option with property key "dont_save_no_sensitive_hit_events"
that can be set in the main configuration file (section "manager").
Default value is "false", meaning event without any hit are saved (no hits == empty event).

Example:
```
[name="manager"]

#@description Prevent from saving events without any sensitive hit
dont_save_no_sensitive_hit_events : boolean = true
```
