### ISSUE TITLE
opening brio files through network (eg. xrootd)

### ISSUE THREAD

**Issue by emchauve** [BxCppDev/Bayeux#26]
We will need the modification bellow on the BRIO reader in order to handle files through network (`TFile::Open` must be called instead of `new TFile`). Typically accessing to xroot disk cache for HPSS files @ CC/IN2P3. 

```
--- a/source/bxbrio/src/reader.cc
+++ b/source/bxbrio/src/reader.cc
@@ -191,7 +191,7 @@ namespace brio {
                      << "' is not recommended !");
     }
     std::string mode("READ");
-    _file = new TFile(_filename.c_str(), mode.c_str());
+    _file = TFile::Open(_filename.c_str(), mode.c_std());
     DT_THROW_IF(_file == 0,
                 std::runtime_error,
                 "Cannot open file '" << _filename << "' !");
```

I can prepare the pull request, but need to be added at developper of Bayeux!! :)

**Comment by xgarrido** [comment]
You do not need to be a Bayeux's developper to create a pull request. You need to fork the repository then on your own fork, create a branch such as "feature-support-xrootd" and then create a pull request.

**Comment by fmauger** [comment]
Done in develop.

**Comment by emchauve** [comment]
i found finally the issue!!

source/bxdpp/src/simple_data_source.cc and source/bxdpp/src/simple_brio_data_source.cc  is handling case where data file path start with "file://", "https://", "ftp://", etc but not "root://"

in addition, we have to skip the check "boost::filesystem::exists(_filename)" in case of XROOTD as we can not probe existence of this file in the usual way
