### ISSUE TITLE
Finish parsing implementation of id_selector in initialize method with datatools::properties

### ISSUE THREAD

**Issue by goliviero** [BxCppDev/Bayeux#4]
On ``id_selector.cc `` in the method : 
 `` void id_selector::initialize(const datatools::properties & config_) ``
Only unique value for given address is parsed.
It will be useful if addresses range and list are parsed too for selection rules with a datatools::properties configuration object

**Comment by fmauger** [comment]
Impacted class is: geomtools::id_selector

**Comment by fmauger** [comment]
New implementation supports the following additional syntax:
 ```
category           : string = "detector"  # Detection unit
address.row.set    : string = "{1}"       # Row #1
address.column.set : string = "[0;4]"     # Column from #0 to #4
```
