### ISSUE TITLE
List of all supported/deprecated directives in properties/multiproperties?

### ISSUE THREAD

**Issue by drbenmorgan** [BxCppDev/Bayeux#42]
For SuperNEMO, I need to add documentation on properties/multiproperties syntax. Could we get a list of the supported/valid directives please? 

The text in https://github.com/BxCppDev/Bayeux/blob/97419aa06a7811a1cb7a5006f67e17cc670ac5db/source/bxdatatools/include/datatools/properties.h#L488 is reasonably clear, but the code would suggest some such as "#@topic" are not used, or not documented adequately.

Edit: Also, what about the "#@ include" directive? This would be useful to support composed workflows.

**Comment by fmauger** [comment]
Additional comments in properties.h files.

**Comment by drbenmorgan** [comment]
Thanks! That covers the main issues.
