### ISSUE TITLE
Warning on use of bitwise or on non-zero value in mygsl

### ISSUE THREAD

**Issue by drbenmorgan** [BxCppDev/Bayeux#62]
In working through warnings on #61, one that popped up that I wasn't 100% sure how to resolve is this

```console
[399/1188] Building CXX object source/CMakeFiles/Bayeux.dir/bxmygsl/src/seed_manager.cc.o
../source/bxmygsl/src/seed_manager.cc:139:25: warning: bitwise or with non-zero value always evaluates to true [-Wtautological-bitwise-compare]
  if (_init_seed_flags_ | INIT_SEED_FROM_RANDOM_DEVICE) {
      ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Looking at the context:

https://github.com/BxCppDev/Bayeux/blob/a1d81bd55f4de7c94010393f836a84b530e06a98/source/bxmygsl/src/seed_manager.cc#L139-L142

it _looks_ like the logic should be bitwise and rather than or?

**Comment by fmauger** [comment]
This is a typo. Should be and (&). I fix it.
