### ISSUE TITLE
bxvariant_inspector failed to identify errors in variant profile

### ISSUE THREAD

**Issue by lemiere** [BxCppDev/Bayeux#7]
I did : 
bxvariant_inspector --load-dll Falaise@$(flquery --libdir) --variant-config @falaise:config/snemo/demonstrator/simulation/geant4_control/2.1/variants/repository.conf --datatools::resource-path falaise@$(flquery --resourcedir) --variant-load toto.prof --variant-gui --variant-store titi.prof --variant-logging trace

Here, the output : 
[inspector.txt](https://github.com/BxCppDev/Bayeux/files/1092096/inspector.txt)

**Comment by fmauger** [comment]
These bugs are about to be fixed in the develop branch.

**Comment by fmauger** [comment]
fixed
