### ISSUE TITLE
[bxdatatools] Validity of range classes

### ISSUE THREAD

**Issue by xgarrido** [BxCppDev/Bayeux#8]
I'm wondering if this logic test https://github.com/BxCppDev/Bayeux/blob/develop/source/bxdatatools/src/real_range.cc#L51 should be replaced by an `or` operator and not an `and` operator. I think the range classes (same issue with `integer_range` class) may be only defined by one of its bound (lower or upper) and, as far as I can see, the `has` function can work with only one of the bounds.

**Comment by fmauger** [comment]
After discussion, we have checked the method is correct.
